### ISSUE TITLE
[Poster account deleted.]

### ISSUE THREAD

**Issue by dev9** [iver56/emoji-art-generator#8]
[Account deleted.]

**Comment by iver56** [comment]
I'm glad to hear that you enjoyed this little project :)

As far as I know, I've already picked the lowest-hanging fruit when it comes to performance. I don't think multiprocessing will help much. However, if done properly, there is some performance to be gained if you can write code that evaluates multiple individuals at the same time within each generation.

Indeed, the algorithm will be quite slow if your image is 1500x1500. It'll be faster if you resize it down to something like 400x400. The various fitness evaluators vary in speed. For example, RGBMSEFitnessEvaluator can be quite fast, since that doesn't involve expensive color conversions or structural similarity computations. But then again, that also seems like the worst of the five implemented fitness evaluators.

If you know other languages, like Go, Rust or Julia, you'll be able to write faster implementations there. Alternatively, if you're familiar with GPU programming (think tensorflow, pytorch or CUDA), that may be a possible way to go.

Another option is to use a different algorithm. Perhaps smarter and less random. Give it some heuristics that show which tiles fit well where.

**Comment by iver56** [comment]
If you do end up downsizing your target image, note that the repository contains some undocumented code that can still render the end result in high resolution :)

See upscale.py

**Comment by dev9** [comment]
Terrific! Thanks so much for taking the time to share those leads -- starting experimenting now. I've already learned so much more about Python thanks to this project!
